config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'departments#mainpage', as: 'home'

  get 'departments/mainpage'

  get 'user_project_details/new', as: 'new'

  delete 'user_project_details/destroy'

  resources :users

  resources :departments

  resources :projects

  resources :user_project_details

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :project
  has_many :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :department
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :department
  has_and_belongs_to_many :project
end

app/models/user_project_detail.rb
class UserProjectDetail < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def mainpage
  end

  def index
    @department = Department.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def new
    @department = Department.new
  end

  def create
    #render plain: params[:tag].inspect
    @department = Department.new(department_params)
    if(@department.save)
      redirect_to @department, notice: 'New department created successfully.'
    else
      render 'new'
    end
  end

  def show
    @department = Department.find(params[:id])
    @user = User.where(:department_id => @department.id).select('name,gender')
    @project = Project.where(:department_id => @department.id).select('projectname,title')
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find_by(params[:id])
      if(@department.update(department_params))
        redirect_to @department, notice: 'Department updated successfully.'
      else
        render 'edit'
      end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    redirect_to departments_path,  notice: 'Department deleted successfully.'
  end

  private def department_params
      params.require(:department).permit(:departmentname)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      @project = Project.order('created_at DESC')
      respond_to do |format|
        format.html
        format.xlsx
      end
    end

    def new
      @project = Project.new
      @department = Department.all
    end

    def create
      #render plain: params[:tag].inspect
      @project = Project.new(project_params)
      if(@project.save)
        redirect_to @project, notice: 'New User created successfully.'
      else
        render 'new'
      end
    end

    def show
      @project = Project.find(params[:id])
      @department = Department.find_by(:id => @project.department_id)
      @user = UserProjectDetail.where(project_id: @project.id).pluck(:user_id)
      @users = User.where(:id => @user).select('id,name,gender')
    end

    def edit
      @project = Project.find(params[:id])
      @department = Department.all
  end

    def update
      @project = Project.find_by(params[:id])
        if(@project.update(project_params))
          redirect_to @project, notice: 'User Detail updated successfully.'
        else
          render 'edit'
        end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      redirect_to projects_path,  notice: 'User Detail deleted successfully.'
    end

    def display

    end

  private def project_params
    params.require(:project).permit(:projectname)
  end
end

app/controllers/user_project_details_controller.rb
class UserProjectDetailsController < ApplicationController
  def new
    @user_project_detail = UserProjectDetail.new
    @project = Project.all
    @user = User.all
  end

  def create
    #render plain: params[:userprojectdetail].inspect
    @user_project_detail = UserProjectDetail.new(userprojectdetail_params)
    if(@user_project_detail.save)
      redirect_to departments_mainpage_path, notice: 'Particular user assigned Particular project successfully.'
    else
      render 'new'
    end
  end

  def destroy
    @user_id = User.find(params[:id => :user_id])
    @project_id = Project.find(params[:id => :project_id])
    UserProjectDetail.where(:user_id => @user_id).where(:project_id => @project_id).destroy
  end

  private def userprojectdetail_params
    params.require(:user_project_detail).permit(:project_id,:user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def new
    @user = User.new
    @department = Department.all
  end

  def create
    #render plain: params[:tag].inspect
    @user = User.new(user_params)
    if(@user.save)
      redirect_to @user, notice: 'New User created successfully.'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @department = Department.find_by(:id => @user.department_id)
    @project = UserProjectDetail.where(user_id: @user.id).pluck(:project_id)
    @projects = Project.where(:id => @project).select('id,projectname,title')
  end

  def edit
    @user = User.find(params[:id])
    @department = Department.all
end

  def update
    @user = User.find_by(params[:id])
      if(@user.update(user_params))
        redirect_to @user, notice: 'User Detail updated successfully.'
      else
        render 'edit'
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path,  notice: 'User Detail deleted successfully.'
  end

  private def user_params
      params.require(:user).permit(:name,:gender,:department_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_project_details_helper.rb
module UserProjectDetailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/edit.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">Edit Department</h3>

<%= form_for @department, url: department_path do |f| %>

<p>
  <%= f.label :departmentname ,"Department Name" %><br>
  <%= f.text_field :departmentname , required: true %>
</p>
<p>
  <%= f.submit("Update Department",{:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">DEPARTMENT DETAILS</h3>
<%= link_to "Add Department" ,new_department_path, :class => 'btn btn-outline-primary' %>
<br/>
<div class="text-center">
<%= link_to 'Download as .xlsx for Departments', departments_path(format: :xlsx), :class => 'btn btn-outline-primary' %>
</div>
<br/>
<% @department.each do |department| %>
<div class="card body">
  <h3> Department Name : <%= department.departmentname %></h3>
  <%= link_to "Read More" ,department_path(department), :class => 'btn btn-outline-primary' %>
</div>
<br>
<% end %>
<br/>

app/views/departments/mainpage.html.erb
<p id="notice"><%= notice %></p>
<div class="card body">
  <%= link_to "DEPARTMENT" ,departments_path, :class => 'btn btn-outline-primary' %>
</div>
<br/>
<div class="card body">
  <%= link_to "USER" ,users_path, :class => 'btn btn-outline-primary' %>
</div>
<br/>
<div class="card body">
  <%= link_to "PROJECT" ,projects_path, :class => 'btn btn-outline-primary' %>
</div>
<br/>

app/views/departments/new.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">Add New Department</h3>

<%= form_with model: @department do |f| %>
<% if @department.errors.any? %>
    <% @department.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
<p>
  <%= f.label :departmentname,"Department Name" %><br>
  <%= f.text_field :departmentname , required: true %>
</p>
<p>
  <%= f.submit("Add Department", {:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>
<br/>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h3>Department Name : <%= @department.departmentname %></h3>
<%= link_to "Edit", edit_department_path(@department), :class => 'btn btn-outline-primary' %>
<%= link_to "Delete", department_path(@department), method: :delete, data: {confirm: 'Are You Sure?'}, :class => 'btn btn-outline-danger' %>
</div>
<hr>
<h3>User Details</h3>
<% @user.each do |user| %>
<div class="card body">
  <h4> User Name : <%= user.name %></h4>
  <p>Gender : <%= user.gender %></p>
</div>
<br/>
<% end %>
<hr>
<h3>Project Details</h3>
<% @project.each do |project| %>
<div class="card body">
  <h4> Project Name : <%= project.projectname %></h4>
  <p> Title : <%= project.title %></p>
</div>
<br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manytomany</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
      COMPANY PROJECT AND USER DETAILS
    </h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to "HOME" ,home_path , :class => 'btn btn-lg btn-block btn-outline-primary' %>
    </nav>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to "Add User - Project" ,new_path , :class => 'btn btn-lg btn-block btn-outline-primary' %>
    </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    </body>
</html>

app/views/projects/edit.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">Edit Project Detail</h3>
<%= form_for @project, url: project_path do |f| %>
<p>
  <%= f.label :projectname ,"Project Name" %><br>
  <%= f.text_field :projectname , required: true %>
</p>
<p>
  <%= f.label :title,"Title" %><br>
  <%= f.text_field :title , required: true %>
</p>
<p>
  <%= f.label :department,"Department" %>
  <%= f.collection_select :department_id, Department.order(:departmentname),:id,:departmentname, :prompt => 'Select' %>
</p>
<p>
  <%= f.submit("Update Project",{:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">PROJECT DETAILS</h3>
<%= link_to "Add Project" ,new_project_path(@department), :class => 'btn btn-outline-primary' %>
<div class="text-center">
<%= link_to 'Download as .xlsx for Projects', projects_path(format: :xlsx), :class => 'btn btn-outline-primary' %>
</div>
<br/>
<% @project.each do |project| %>
<div class="card body">
  <h3> Project Name : <%= project.projectname %></h3>
  <%= link_to "Read More" ,project_path(project), :class => 'btn btn-outline-primary' %>
</div>
<br/>
<% end %>

app/views/projects/new.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">Add New User</h3>
<%= form_with model: @project do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
<p>
  <%= f.label :projectname,"Project Name" %><br>
  <%= f.text_field :projectname , required: true %>
</p>
<p>
  <%= f.label :title,"Title" %><br>
  <%= f.text_field :title , required: true %>
</p>
<p>
  <%= f.label :department,"Department" %>
  <%= f.collection_select :department_id, Department.order(:departmentname),:id,:departmentname, :prompt => 'Select' %>
</p>
<p>
  <%= f.submit("Add Project", {:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>
<br/>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h3>Project Name : <%= @project.projectname %></h3>
<h3>Title : <%= @project.title %></h3>
<h3>Department : <%= @department.departmentname %></h3>
<%= link_to "Edit", edit_project_path(@project), :class => 'btn btn-outline-primary' %>
<%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: 'Are You Sure?'}, :class => 'btn btn-outline-danger' %>
</div>
<hr>
<h3><%= @project.projectname %>- User Details</h3>
<% @users.each do |user| %>
<div class="card body">
  <h4> User Name : <%= user.name %></h4>
  <p> Gender : <%= user.gender %>

      <%= link_to '[X]', method: :delete,
                              data: { confirm: 'Are you sure?'} %>
  </p>
</div>
<br/>
<% end %>

app/views/user_project_details/new.html.erb
<p id="notice"><%= notice %></p>
<%= form_with model: @user_project_detail do |f| %>
<p>
  <%= f.label :project_id,"Project" %>
  <%= f.collection_select :project_id, Project.order(:projectname), :id, :projectname, :prompt => 'Select' %>
</p>
<p>
  <%= f.label :user_id,"User" %>
  <%= f.collection_select :user_id, User.order(:name), :id, :name, :prompt => 'Select' %>
</p>
<p>
  <%= f.submit("Add Project for User", {:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">Edit User Detail</h3>
<%= form_for @user, url: user_path do |f| %>
<p>
  <%= f.label :name ,"User Name" %><br>
  <%= f.text_field :name , required: true %>
</p>
<p>
  <%= f.label :gender,"Gender" %><br>
  <%= f.text_field :gender , required: true %>
</p>
<p>
  <%= f.label :department,"Department" %>
  <%= f.collection_select :department_id, Department.order(:departmentname),:id,:departmentname, :prompt => 'Select' %>
</p>
<p>
  <%= f.submit("Update User",{:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">USER DETAILS</h3>
<%= link_to "Add User" ,new_user_path, :class => 'btn btn-outline-primary' %>
<br/>
<div class="text-center">
<%= link_to 'Download as .xlsx for Users', users_path(format: :xlsx), :class => 'btn btn-outline-primary' %>
</div>
<br/>
<% @user.each do |user| %>
<div class="card body">
  <h3> User Name : <%= user.name %></h3>
  <%= link_to "Read More" ,user_path(user), :class => 'btn btn-outline-primary' %>
</div>
<br/>
<% end %>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">Add New User</h3>
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
<p>
  <%= f.label :name,"User Name" %><br>
  <%= f.text_field :name , required: true %>
</p>
<p>
  <%= f.label :gender,"Gender" %><br>
  <%= f.text_field :gender , required: true %>
</p>
<p>
  <%= f.label :department,"Department" %>
  <%= f.collection_select :department_id, Department.order(:departmentname),:id,:departmentname, :prompt => 'Select' %>
</p>
<p>
  <%= f.submit("Add User", {:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>
<br/>
`

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h3>User Name : <%= @user.name %></h3>
<h3>Gender : <%= @user.gender %></h3>
<h3>Department : <%= @department.departmentname %></h3>
<%= link_to "Edit", edit_user_path(@user), :class => 'btn btn-outline-primary' %>
<%= link_to "Delete", user_path(@user), method: :delete, data: {confirm: 'Are You Sure?'}, :class => 'btn btn-outline-danger' %>
</div>
<hr>
<h3><%= @user.name %>- Project Details</h3>
<% @projects.each do |project| %>
<div class="card body">
  <h4> Project Name : <%= project.projectname %></h4>
  <p> Title : <%= project.title %>

      <%= link_to '[X]', method: :delete,
                              data: { confirm: 'Are you sure?'} %>
  </p>
</div>
<br/>
<% end %>